Repository FilipParyz/TestingDoggos, pull requests merged in 2024-04, with the labels that each got.

#21 Flexboxed profiles and contact as well as customized scroll
  static/css/contactstyle.css
  static/css/profileinfostyle.css
  static/css/sidebarstyle.css
  static/css/style.css
  static/css/support_us.css
  static/images/profiles/1MP_buttonpair_pic.png
  static/images/profiles/2MP_buttonpair_pic.png
  static/images/profiles/3MP_buttonpair_pic.png
  static/images/profiles/4MP_buttonpair_pic.png
  static/images/profiles/5MP_buttonpair_pic.png
  templates/index.html
Labels: documentation, enhancement, fix

#22 Update README.md
  README.md
Labels: documentation

#25 Removed tests running on PRs
  .github/workflows/run_tests.yml
Labels: fix

#26 Added autopep8 and pylint
  .github/workflows/codecheck.yml
Labels: enhancement

#27 Changes to conform to newly added workflow
  .github/workflows/codecheck.yml
  .github/workflows/run_tests.yml
  README.md
  testing_doggos.py
  tests.py
Labels: fix

#28 Pushing autopep automated changes
  .github/workflows/codecheck.yml
  testing_doggos.py
  tests.py
Labels: bug

#29 Dividied workflows
  .github/workflows/autopep8.yml
  .github/workflows/codecheck.yml
  .github/workflows/pylint.yml
  .github/workflows/python_tests.yml
  README.md
Labels: enhancement

#30 Update README.md pylint
  README.md
Labels: documentation

#31 Added template manage_food, routing, and button in .js, added cons…
  static/css/style.css
  static/js/script.js
  templates/index.html
  templates/manage_food.html
  testing_doggos.py
Labels: enhancement

#35 Structure improvements and Icon
  static/css/contact-style.css
  static/css/profile-style.css
  static/css/style.css
  static/images/Icon/apple-touch-icon-144x144.png
  static/images/Icon/apple-touch-icon-152x152.png
  static/images/Icon/favicon-16x16.png
  static/images/Icon/favicon-32x32.png
  static/images/Icon/favicon.ico
  static/images/Icon/mstile-144x144.png
  static/images/Picture.png
  static/js/script.js
  templates/index.html
  templates/profile_page.html
  testing_doggos.py
Labels: enhancement
