Repository FilipParyz/TestingDoggos, pull requests merged in 2024-03, with the labels that each got.

#3 Adding frontend
  TestingDoggos.py
  static/css/style.css
  static/images/Call.png
  static/images/CatProfile.png
  static/images/Charity.png
  static/images/Heartwithdogpaw.png
  static/images/KawaiiSteak.png
  static/images/Login.png
  static/images/Pets.png
  static/images/Picture.png
  static/images/Search.png
  static/js/script.js
  templates/index.html
Labels: enhancement

#4 README changes, added new sections with information
  README.md
Labels: enhancement

#5 Front With details widget
  static/css/infostyle.css
  static/css/style.css
  static/js/script.js
  templates/index.html
Labels: enhancement

#6 Improvement of adding new attributes for new widgets and pages
  TestingDoggos.py
  static/css/buttonsstyles.css
  static/css/infostyle.css
  static/css/profilestyle.css
  static/css/sidebarstyle.css
  static/css/style.css
  static/images/Contactinfo_line_Address_pic.png
  static/images/Contactinfo_line_Email_pic.png
  static/images/MF_1stbuttonpair_pic.png
  static/images/MF_3rdbuttonpair_pic.png
  static/images/MF_4thbuttonpair_pic.png
  static/images/MF_5thbuttonpair_pic.png
  static/images/Sidebar/KawaiiSteak.png
  static/images/Sidebar/Pets.png
  static/images/Sidebar/SelectionV3.png
  static/images/Sidebar/Selectionv2.png
  static/images/TopSidebar/Call.png
  static/images/TopSidebar/Charity.png
  static/images/TopSidebar/Heartwithdogpaw.png
  static/images/TopSidebar/Login.png
  static/images/navigation/MF_5thbuttonpair_button_Minus.png
  static/images/navigation/MF_5thbuttonpair_button_Plus.png
  static/images/navigation/MP_1stbuttonpair_button_remove.png
  static/images/navigation/MP_addButton.png
  static/images/navigation/Profile_page_ArrowRight_pic.png
  static/images/navigation/Profile_page_Close_pic.png
  static/images/navigation/Profile_page_Transfer_pic.png
  static/images/navigation/Profile_page__ArrowLeft_pic.png
  static/images/profiles/MP_1stbuttonpair_pic.png
  static/images/profiles/MP_2ndbuttonpair_pic.png
  static/images/profiles/MP_3rdbuttonpair_pair.png
  static/images/profiles/MP_4thbuttonpair_pic.png
  static/images/profiles/MP_5thbuttonpair_pic.png
  static/images/profiles/Picture.png
  templates/MF_button.html
  templates/MP_button.html
  templates/Prototypes/BiggersideWIDGET.txt
  templates/Prototypes/MF_WIDGET.txt
  templates/Prototypes/MP_WIDGET.txt
  templates/Prototypes/SmallerWIDGET.txt
  templates/index.html
  templates/profile_page.html
Labels: enhancement

#9 Mariusz front did id to almost every class and adjusted the CSS's
  static/css/sidebarstyle.css
  static/css/style.css
  static/js/script.js
  templates/index.html
Labels: documentation, fix

#12 Adjustment of profile data widget
  static/css/infostyle.css
  templates/index.html
Labels: enhancement, fix

#13 Backend fixes and integration
  README.md
  TestingDoggos.py
  requirements.txt
  static/js/script.js
  templates/index.html
Labels: enhancement

#15 Fixed README
  README.md
Labels: bug

#17 Adding new workflow with automated tests
  .github/workflows/run_tests.yml
Labels: enhancement

#16 Addition form
  TestingDoggos.py
  static/js/script.js
  templates/index.html
  templates/manage_animals.html
Labels: enhancement
